#!/bin/bash

# First use powerpoint to export the slides to PDF 
# Note: export to PDF, not print to PDF, otherwise trimming will not work.

if [[ ! -e figures.pdf ]]; then
    echo "PDF does not exist; export Powerpoint to PDF first (export, don't print!)"
    exit 1
fi

if [[ figures.pptx -nt figures.pdf ]]; then
    echo "Powerpoint is newer than PDF; export Powerpoint to PDF first (export, don't print!)"
    exit 1
fi

echo "Converting PDF to PNG"
magick convert -density 300 -units pixelsperinch -trim +profile "icc" figures.pdf figures.png

echo "Renaming files"
mv figures-0.png when-is-q-day.png
mv figures-1.png wireshark-started.png
mv figures-2.png wireshark-trace.png
mv figures-3.png swagger-docs.png
mv figures-4.png topology.png
mv figures-5.png client-to-hub-relaying.png
mv figures-6.png hub-to-client-relaying.png
mv figures-7.png trusted-relay-node.png
mv figures-8.png message-signing.png
mv figures-9.png ladder-diagram-startup.png
mv figures-10.png ladder-diagram-get-key.png
mv figures-11.png psrd-management-classes.png
