name: Workflow that runs on every push.
run-name: ${{ github.actor }} pushed to ${{ github.ref }}
on: [push, pull_request, workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code and set up Python
      uses: actions/checkout@v4
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
      run: python -m venv venv
      run: source venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt
    - name: Check code and run
      run: source venv/bin/activate && scripts/check-and-test --verbose
    - name: Collect information useful for debugging
      if: always()
      run: for f in *.out ; do echo === $f ===; cat $f ; done
